spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ProjetoSpring
    username: postgres
    password: admin


## Hibernate Properties	
# The SQL dialect makes Hibernate generate better SQL for the chosen database	
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect



